name: Build Native Applications

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact-name: fingerprintbrowser-linux
          - os: windows-latest
            platform: windows
            artifact-name: fingerprintbrowser-windows
          - os: macos-latest
            platform: macos
            artifact-name: fingerprintbrowser-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean compile

    - name: Create runtime image
      run: mvn javafx:jlink

    - name: Create native package (Windows)
      if: matrix.platform == 'windows'
      run: mvn jpackage:jpackage@win

    - name: Create native package (macOS)
      if: matrix.platform == 'macos'
      run: mvn jpackage:jpackage@mac

    - name: Create native package (Linux)
      if: matrix.platform == 'linux'
      run: mvn jpackage:jpackage@linux

    - name: Find package file (Windows)
      if: matrix.platform == 'windows'
      run: |
        $files = Get-ChildItem -Path "target/dist" -Filter "*.exe" -Recurse
        if ($files.Count -gt 0) {
          echo "PACKAGE_FILE=$($files[0].FullName)" >> $env:GITHUB_ENV
          echo "PACKAGE_NAME=$($files[0].Name)" >> $env:GITHUB_ENV
        }

    - name: Find package file (macOS)
      if: matrix.platform == 'macos'
      run: |
        if [ -d "target/dist/FingerprintBrowser.app" ]; then
          cd target/dist
          tar -czf FingerprintBrowser-macos.tar.gz FingerprintBrowser.app
          echo "PACKAGE_FILE=$(pwd)/FingerprintBrowser-macos.tar.gz" >> $GITHUB_ENV
          echo "PACKAGE_NAME=FingerprintBrowser-macos.tar.gz" >> $GITHUB_ENV
        fi

    - name: Find package file (Linux)
      if: matrix.platform == 'linux'
      run: |
        files=$(find target/dist -name "*.deb" -o -name "*.rpm" | head -1)
        if [ -n "$files" ]; then
          echo "PACKAGE_FILE=$files" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(basename $files)" >> $GITHUB_ENV
        fi

    - name: Upload artifacts
      if: env.PACKAGE_FILE != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: ${{ env.PACKAGE_FILE }}
        retention-days: 30

    - name: Upload to release
      if: github.event_name == 'release' && env.PACKAGE_FILE != ''
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PACKAGE_FILE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}